### ISSUE TITLE
Initialize the mobile, frontend, and backend sides of the projects

### ISSUE THREAD

**Issue by e-taha** [bounswe/bounswe2024group12#114]
## Description

Main issue to track the initialization of the mobile, frontend, and backend sides of the project.

***

## Sub-Issues
- [ ] Initialize the Mobile side of the project
- [ ] Initialize the Frontend side of the project
- [ ] Initialize the Backend side of the project

***

### Reviewer:
This issue will be reviewed by: _@e-taha

**Comment by isilsukarakuzuu** [comment]
We did a meeting today with backend team (@ArdaYalcindag @mbatuhancok). We will initialize the backend part of the project this week, possibly on Wednesday after fishing sequence diagrams.

**Comment by isilsukarakuzuu** [comment]
It is initialized, after @ahmetfirat23 and @e-taha 's reviews, we can close this issue.

**Comment by ahmetfirat23** [comment]
This issue is complete and forgotten sorry
