### ISSUE TITLE
Milestone 2 Report 

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#183]
## Description

Initialize Milestone 2 Report and add titles and subtitles. Follow each section of report.

***

## Acceptance Criteria
- [x] Milestone 2 Report is initialized.
<br>

## Sub-Issues
- [x] Write Executive Summary.
- [x] Write Contributions by Team Members.
<br>

***

### Reviewer:
This issue will be reviewed by: @ahmetfirat23 @sonerkuyar

**Comment by isilsukarakuzuu** [comment]
I initialized the report that we write, It's due to this Friday. Let's divide sections.

**Comment by isilsukarakuzuu** [comment]
Added Django, Postman, GitHub and Discord as tools. I will add Docker also. Then I will write the parts "evaluation of processes" and "what we learned so far?".

@ahmetfirat23 @asyasusen @sonerkuyar @yusufaygun Could someone from your side fill in the part related to React? I couldn't write it because I haven't used it.

@e-taha @abayir41 @ounuvar Also could someone from your side fill in the part related to React Native?

@ahmetfirat23 Do you want to fill out Digital Ocean part since you successfully managed to deploy our project 😄 ?

**Comment by isilsukarakuzuu** [comment]
I added Docker in "Evaluation of Tools" and wrote "Evaluation of Processes".

Now I will add "What We Learned So Far?" and "Challenges Encountered" parts.

**Comment by ahmetfirat23** [comment]
> Added Django, Postman, GitHub and Discord as tools. I will add Docker also. Then I will write the part "Evaluation of Processes".
> 
> @ahmetfirat23 @asyasusen @sonerkuyar @yusufaygun Could someone from your side fill in the part related to React? I couldn't write it because I haven't used it.
> 
> @e-taha @abayir41 @ounuvar Also could someone from your side fill in the part related to React Native?
> 
> @ahmetfirat23 Do you want to fill out Digital Ocean part since you successfully managed to deploy our project 😄 ?

The issue with deployment was mostly Docker based so I am not that proficient with Digital Ocean. I think @e-taha and you have more comprehensive information about the platform so it would be better if you could fill that part. I believe @sonerkuyar has the insights to write about React. Moreover, I have allocated extensive amount of time and effort this week so I would like to refrain writing a part for the report except personal contributions. Since you already created an outline and we didn't have a team meeting this week I think you can assign parts to team members yourself. If anything urgent comes up please still contact me. 
@isilsukarakuzuu

**Comment by ahmetfirat23** [comment]
Another important thing is that; last time, we had submission issues due to its being left to the last minute. This time to prevent similar problems, I am planning to personally submit the report one hour before the deadline. Please plan ahead accordingly.
@bounswe/bounswe2024group12

**Comment by ahmetfirat23** [comment]
Finally, as I said I created an hackmd link for collaborative editing of milestone report. I will be sending it from Whatsapp.

**Comment by isilsukarakuzuu** [comment]
I wrote parts from 1.4 to 1.8 excluding React and React Native. @ArdaYalcindag @mbatuhancok @asyasusen @yusufaygun if one of you can proofread it I would appreciate that. Now I'm writing 1.1, Could someone from you take a look at 1.2 and 1.3?

**Comment by ahmetfirat23** [comment]
I wrote 1.2 and 1.3 and my contributions. Enjoy.

**Comment by asyasusen** [comment]
> I wrote parts from 1.4 to 1.8 excluding React and React Native. @ArdaYalcindag @mbatuhancok @asyasusen @yusufaygun if one of you can proofread it I would appreciate that. Now I'm writing 1.1, Could someone from you take a look at 1.2 and 1.3?

Everything looks okay I've fixed the grammer mistakes I saw

**Comment by ounuvar** [comment]
I wrote 1.7.1.5 (React Native part) and my contributions.

**Comment by ahmetfirat23** [comment]
@isilsukarakuzuu submitted the report.
