### ISSUE TITLE
Authorize IGDB and get Access Token

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#188]
## Description

We need an access to IGDB API to get features of Games but IGDB API needs authorization. Access token and Client ID from Twitch is needed to make API requests. 

***

## Acceptance Criteria
- [x] Sign Up with [Twitch](https://dev.twitch.tv/login) for a free account
- [x] Ensure you have Two Factor Authentication [enabled](https://www.twitch.tv/settings/security)
- [x] Register your application in the [Twitch Developer Portal](https://dev.twitch.tv/console/apps/create)
- [x] [Manage](https://dev.twitch.tv/console/apps) your newly created application
- [x] Generate a Client Secret by pressing [New Secret]
- [x] Take note of the Client ID and Client Secret
- [x] Make a POST request to https://id.twitch.tv/oauth2/token with the following query string parameters, substituting your Client ID and Client Secret accordingly.
> client_id=Client ID
> client_secret=Client Secret
> grant_type=client_credentials

<br>

## Sub-Issues
- [x] #189 (Not a direct sub issue)
<br>

**Comment by isilsukarakuzuu** [comment]
I did the following steps. You can access a test connection under our Postman workspace @mbatuhancok @ArdaYalcindag. Also I shared the links, IDs and tokens with you privately. For further info, check [IGDB API Documentation](https://api-docs.igdb.com/).

**Comment by isilsukarakuzuu** [comment]
Also it needs test in deployment since IGDB API works with http:// in localhost but It doesn't accept other http:// requests. We need to deploy our project in https://, I'm not sure how to do it, I will open a sub-issue for that @ahmetfirat23 @yusufaygun.

**Comment by ahmetfirat23** [comment]
> Also it needs test in deployment since IGDB API works with http:// in localhost but It doesn't accept other http:// requests. We need to deploy our project in https://, I'm not sure how to do it, I will open a sub-issue for that @ahmetfirat23 @yusufaygun.

that sounds something important, please go ahead and open an issue. i will try to take care of it with authorization stuff until monday night hopefully.

**Comment by isilsukarakuzuu** [comment]
> > Also it needs test in deployment since IGDB API works with http:// in localhost but It doesn't accept other http:// requests. We need to deploy our project in https://, I'm not sure how to do it, I will open a sub-issue for that @ahmetfirat23 @yusufaygun.
> 
> that sounds something important, please go ahead and open an issue. i will try to take care of it with authorization stuff until monday night hopefully.

I opened it, we can continue from #189

**Comment by isilsukarakuzuu** [comment]
Since we didn't use IGDB API and only used Wikidata API, I'm lowering the priority of this issue.

**Comment by isilsukarakuzuu** [comment]
Changing deployment protocol is not a direct sub issue for this issue and this issue is done what it's expected to do, so I'm closing this issue.
