### ISSUE TITLE
Create An Extensive Project Plan

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#257]
## Description

We should create a project plan with a roadmap and set milestones. RAM is also needed. 

***

## Acceptance Criteria
- [x] A new RAM page is created and added to the sidebar. #273
- [x] A new GitHub Project is created and initialized with milestones and expected dates, a roadmap is created. #272 
- [ ] The open issues are added to the new project and assigned proper deadlines.
<br>

***

### Reviewer:
This issue will be reviewed by: @ahmetfirat23

**Comment by sonerkuyar** [comment]
Due to this issue is complex and requires also team decision in it,  I created a new issue which describes the formal part of creating new Github Project ( #272 ) and RAM ( #273) then assigned it to myself.

**Comment by sonerkuyar** [comment]
I created Project Plan Page and added to the wiki. [Project Plan](https://github.com/bounswe/bounswe2024group12/wiki/Project-Plan-CMPE451)

**Comment by ahmetfirat23** [comment]
I won't close this issue until we properly use start and end dates. Please kindly use it!
