### ISSUE TITLE
Initialize the Project Codebase

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#262]
## Description

We should initialize our codebase with selected tools. Frontend, Backend and Mobile directories should be initialized. Also a database system needs to be included. 

***

## Acceptance Criteria
- [x] A codebase for Frontend is initialized.
- [x] A codebase for Backend is initialized.
- [x] A codebase for Mobile is initialized.
- [x] A database system is added.
- [x] Correct file hierarchy and branch system is created.
<br>

## Sub-Issues
- [x] #258 
- [x] #259 
- [x] #260 
- [x] #261 

<br>

***

### Reviewer:
This issue will be reviewed by: _reviewers needed_

**Comment by isilsukarakuzuu** [comment]
We did frontend with @ahmetfirat23

**Comment by ahmetfirat23** [comment]
I think this issue is completed.
