### ISSUE TITLE
Requirements Elicitation

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#276]
# Requirements Elicitation

## Overview
This is a parent issue which organizes Requirements Elicitation Phase of the project. We made some researches to accomplish what we need for the project.

### Domain Analysis
- [x] Perform an analysis of the domain by examining related software systems(lichess API, Wikidata API).
- [ ] Document observations of their features, specifically noting what is missing.

### Requirements Specification
- [x] Identify and specify the requirements for the project.
- [x] Document the requirements directly in the project repository using Wiki syntax. Do not link to external documents. You may upload supplemental information, but the main requirements must be written in the Wiki.

### Scenarios and Mockups
- [x] Create detailed scenarios describing specific personas and their activities within the system.
- [ ] Design high-level mockups of envisioned interactions with the system, supporting the scenarios described.

## Deliverables
- [x] For each objectives deliverables will be put under Wiki's page.

## Sub-Issues Checklist
All the sub-issues related to the requirements elicitation phase. 
## Sub-Issues Checklist
All the sub-issues related to the requirements elicitation phase. 
- #256
- #263
- #264
