### ISSUE TITLE
Write Milestone 2 Report

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#349]
## Description
Writing Milestone 2 Report which is described at the Moodle folder. 

***

## Acceptance Criteria
- [ ] Requirements Section Completed
- [ ] Deliverables Section Completed
- [ ] Testing Section Completed
- [ ] Planing and Team Process Section Completed
- [ ] Evaluation Section Completed

### Reviewer:
This issue will be reviewed by: _@username_

**Comment by sonerkuyar** [comment]
- I created initial .md file and prepared report structure as described in the Moodle. 
- Shared the link in WhatsApp with teammates.
- Wrote our testing plan.
- Wrote evaluation of tools
- Wrote evaluation of processes
- Created api doc, reviewed it  and uploaded APi doc into GitHub and add the file link into report.
- Filled my personal spaces

**Comment by ahmetfirat23** [comment]
I have written 3-4 in deliverables, frontend testing, 1 in evaluation and my own section.

**Comment by ahmetfirat23** [comment]
completed but @sonerkuyar can you link the file here?

**Comment by sonerkuyar** [comment]
Due to HackMd is open to everyones editing anonymously I shared it at the WhatsApp group, now I can share [Hackmd-link](https://hackmd.io/C6ej-f1CQHC2ewQ_AMviWw)

> completed but @sonerkuyar can you link the file here?
