### ISSUE TITLE
Write Milestone 3 Report 

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#423]
## Description
Report for Milestone 3 should be written by team members according to document at [Moodle](https://moodle.bogazici.edu.tr/my/). 
Section 2 and 8 will be filled by each member. There are also parts for group works. Each assignee can take the approximately equal work for the sections. In the comment each member should specify which group works(parts) will he/she take.
Here is the Report outline [Outline](https://github.com/bounswe/bounswe2024group12/wiki/Milestone%E2%80%903%E2%80%90Report%E2%80%90451)
Also I shared the Hacked link via WhatsApp.

***

## Acceptance Criteria
- [x] 1. Executive Summary has written.
- [x] 3. Status of Requirements has written.
- [x] 4. Api Endpoints  has written
- [x] 5. UI/UX has written
- [x] 6. Standards has written
- [x] 7. Scenarios has written
- [x] 2nd and 8th section has written by each team member
<br>...

### Reviewer:
This issue will be reviewed by: _@username_

**Comment by sonerkuyar** [comment]
I will complete 4th and 7th headings.

**Comment by ahmetfirat23** [comment]
I will do 3rd part and 5th part for the front end.

**Comment by yusufaygun** [comment]
I can take part 6.

**Comment by ounuvar** [comment]
The complete report is written and submitted under the reports/ directory.
