### ISSUE TITLE
Prepare Milestone 1 Report (Task Sharing)

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#77]
## Description

Assign sections of the Milestone 1 report to team members for collaboration.

***

## Acceptance Criteria
- [x] Each team member receives clear assignments for sections of the Milestone 1 report.
- [x] All team members confirm their understanding and complete their assigned sections.
<br>

**Comment by isilsukarakuzuu** [comment]
It's divided. You can see your tasks here. Please confirm by ticking the box.

## Sub-Issues
- [ ] @ArdaYalcindag -> #78
_Reviewer(s) -> @ounuvar_ 

- [ ] @sonerkuyar -> #79
_Reviewer(s) -> @ounuvar_ 

- [ ] @asyasusen @mbatuhancok @e-taha -> #80
_Reviewer(s) -> @abayir41 @ahmetfirat23 @yusufaygun_ 

- [x] @isilsukarakuzuu -> #81
_Reviewer(s) -> @ahmetfirat23 @ArdaYalcindag_ 

<br>

**Comment by ahmetfirat23** [comment]
Since everyone supposed to write their own work done table can you split these tasks for those people who were assigned

**Comment by isilsukarakuzuu** [comment]
Thank you for informing, I'm splitting the task for 'Table of Work Done by Each Team Member' to each member individually. 

- [ ] @abayir41 : #84
- [ ] @ahmetfirat23 : #85
- [ ] @ArdaYalcindag : #83 
- [ ] @asyasusen : #86
- [ ] @mbatuhancok : #87
- [ ] @isilsukarakuzuu : #88
- [ ] @ounuvar : #89
- [ ] @sonerkuyar : #90
- [ ] @e-taha : #91
- [ ] @yusufaygun : #92

**Comment by ahmetfirat23** [comment]
Everything seems fine.
