### ISSUE TITLE
Research and Planning

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#93]
# Research and Planning 

## Overview
This is a parent issue which organizes Research and Planing Phase of the project. We made some researches to accomplish what we need for the project.

## Objectives
- [x] Research about Wikidata, Linked Data, SPARQL semantic queries, Wikidata API --- Learn and experiment. Put specific queries and responses in your Wiki under "research".
- [x] Research about Mobile application development
- [x] Research about Web application development
- [x] Research about Application Programming Interface (API) .

## Deliverables
- [x] Putting research results under wiki page 

## Sub-Issues Checklist
All the sub-issues related to the research and planning phase. 
- #57 
- #59 
- #52 
- #60 
- #61 
- #56

**Comment by ahmetfirat23** [comment]
This milestone was forgotten as opened. I am closing it since it has been already delivered.
