### ISSUE TITLE
Requirements Elicitation

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#94]
# Requirements Elicitation

## Overview
This is a parent issue which organizes Requirements Elicitation Phase of the project. We made some researches to accomplish what we need for the project.

### Domain Analysis
- [x] Perform an analysis of the domain by examining related software systems.
- [x] Document observations of their features, specifically noting what is missing.

### Requirements Specification
- [x] Identify and specify the requirements for the project.
- [x] Document the requirements directly in the project repository using Wiki syntax. Do not link to external documents. You may upload supplemental information, but the main requirements must be written in the Wiki.

### Questions for Clarification
- [x] Identify a list of questions that need clarification from the customer.
- [x] Document these questions in the project repository for easy reference.

### Scenarios and Mockups
- [x] Create detailed scenarios describing specific personas and their activities within the system.
- [x] Design high-level mockups of envisioned interactions with the system, supporting the scenarios described.

### Presentation and Feedback
- [x] Be prepared to present the requirements and the list of questions to the customer.
- [x] Document the feedback received from the customer during the elicitation phase for future reference and adjustments.

## Deliverables
- [x] For each objectives deliverables will be put under Wiki's page.

## Sub-Issues Checklist
All the sub-issues related to the requirements elicitation phase. 
- #65 
- #66
- #67
- #68
- #69
- #70

**Comment by ahmetfirat23** [comment]
Since all the tasks are completed this part of the project should be closed.
